apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}-{{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      name: {{ .Values.service.http.name }}
    - port: {{ .Values.service.metrics.port }} 
      targetPort: {{ .Values.service.metrics.port }}
      protocol: TCP
      name: {{ .Values.service.metrics.name }}
  selector:
    app: {{ .Release.Name }} 
